/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2017-12-18-e4f4040"
#endif /* AVUTIL_FFVERSION_H */
