/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2018-06-22-ddca3ee6e1"
#endif /* AVUTIL_FFVERSION_H */
